name: file-object-store push CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build in Docker container	    
      uses: docker://mriffle/build-spectr:latest
      with:
        entrypoint: ant
        args: -f ant_build_all.xml
